# Generated by Django 2.2 on 2020-08-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilepic',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Profile_Pic',
        ),
    ]
